import {z} from 'zod';
const money=z.number().int().min(0).max(1000000000);
const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Fecha inválida');
const short=z.string().trim().min(1).max(150), optional=z.string().trim().max(4000).default('');
export const noteSchema=z.object({name:short,customer:short,phone:z.string().max(30).default(''),fragrance:short,formula:optional,volume:z.number().min(1).max(1000),status:z.enum(['En desarrollo','Lista','Entregada']),date:day,notes:optional});
export const orderSchema=z.object({customer:short,phone:z.string().max(30).default(''),note:short,quantity:z.number().int().min(1).max(10000),unitPrice:money,unitCost:money,paid:money,status:z.enum(['Pendiente','En preparación','Entregado','Cancelado']),date:day,notes:optional}).refine(d=>d.paid<=d.quantity*d.unitPrice,'El abono no puede superar el total');
export const expenseSchema=z.object({description:short,category:z.enum(['Esencias','Frascos y empaques','Publicidad','Equipos','Transporte','Otros']),type:z.enum(['Inversión','Gasto operativo']),amount:money,date:day,notes:optional});
export type Kind='notes'|'orders'|'expenses'|'profiles';
export type Row={id:string;kind:Kind;payload:any;revision:number;created_at:string;updated_at:string};
export function parsePayload(kind:Kind,data:unknown){if(kind==='notes')return noteSchema.parse(data);if(kind==='orders')return orderSchema.parse(data);if(kind==='expenses')return expenseSchema.parse(data);throw new Error('Tipo no editable');}
export function summary(rows:Row[],from:string,to:string){const selected=rows.filter(r=>{const date=r.payload.date||r.created_at.slice(0,10);return (!from||date>=from)&&(!to||date<=to);});const orders=selected.filter(r=>r.kind==='orders'&&r.payload.status!=='Cancelado').map(r=>r.payload);const expenses=selected.filter(r=>r.kind==='expenses').map(r=>r.payload);const sales=orders.filter(p=>p.status==='Entregado').reduce((a,p)=>a+p.quantity*p.unitPrice,0),cost=orders.filter(p=>p.status==='Entregado').reduce((a,p)=>a+p.quantity*p.unitCost,0),collected=orders.reduce((a,p)=>a+p.paid,0),due=orders.reduce((a,p)=>a+p.quantity*p.unitPrice-p.paid,0),investment=expenses.filter(p=>p.type==='Inversión').reduce((a,p)=>a+p.amount,0),operating=expenses.filter(p=>p.type==='Gasto operativo').reduce((a,p)=>a+p.amount,0);return {sales,cost,collected,due,investment,operating,margin:sales-cost-operating,count:orders.length,notes:selected.filter(r=>r.kind==='notes').length};}
