import {isAdmin} from '@/lib/admin-store';
import {noteDatabase} from '@/lib/supabase';
import {parsePayload,type Kind} from '@/lib/admin-data';
import {z} from 'zod';
export const dynamic='force-dynamic';
export async function GET(){if(!await isAdmin())return Response.json({error:'Acceso no autorizado'},{status:403});try{const data=await noteDatabase<{rows:unknown[]}>({action:'list'});return Response.json(data,{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'No pudimos cargar los datos. Intenta nuevamente.'},{status:503});}}
const envelope=z.object({id:z.string().uuid(),kind:z.enum(['notes','orders','expenses']),revision:z.number().int().min(1).optional(),payload:z.unknown()});
export async function POST(req:Request){if(!await isAdmin())return Response.json({error:'Acceso no autorizado'},{status:403});if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Solicitud no permitida'},{status:403});try{if(Number(req.headers.get('content-length')||0)>20000)return new Response(null,{status:413});const body=envelope.parse(await req.json());const payload=parsePayload(body.kind as Kind,body.payload);await noteDatabase({action:'save',id:body.id,kind:body.kind,payload,revision:body.revision});return Response.json({ok:true});}catch(e){const status=typeof e==='object'&&e&&'status' in e&&e.status===409?409:400;return Response.json({error:e instanceof z.ZodError?e.issues.map(i=>i.message).join('. '):e instanceof Error&&status===409?e.message:'No pudimos guardar. Tus datos siguen en el formulario.'},{status});}}
export async function DELETE(req:Request){if(!await isAdmin())return Response.json({error:'Acceso no autorizado'},{status:403});if(req.headers.get('origin')!==new URL(req.url).origin)return new Response(null,{status:403});try{const b=z.object({id:z.string().uuid(),revision:z.number().int().min(1)}).parse(await req.json());await noteDatabase({action:'archive',id:b.id,revision:b.revision});return Response.json({ok:true});}catch(e){const status=typeof e==='object'&&e&&'status' in e&&e.status===409?409:503;return Response.json({error:e instanceof Error&&status===409?e.message:'No pudimos archivar el registro.'},{status});}}
